######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 00:58:12 2019
######################################################################

TEMPLATE = app
TARGET = main
INCLUDEPATH += .

# Input
SOURCES += main.cpp luogu/p1001.cpp
